### PR TITLE
Indri working with Robust04

### PR DESCRIPTION
**Pull request by chauff**

### CODE REVIEW

**Comment by ryan-clancy** [comment]
@chauff I get slightly different results when I run it:
```
###
# out/indri/robust.jm0.5.title
###
num_q                   all     249
map                     all     0.2242
P_30                    all     0.2839

###
# out/indri/robust.bm25.title
###
num_q                   all     249
map                     all     0.2338
P_30                    all     0.2995

###
# out/indri/robust.bm25.desc
###
num_q                   all     249
map                     all     0.2702
P_30                    all     0.3274

###
# out/indri/robust.dir1000.title.prf (use_prf=1)
###
num_q                   all     249
map                     all     0.2812
P_30                    all     0.3249

###
# out/indri/robust.dir1000.title.no_prf (use_prf=0)
###
num_q                   all     249
map                     all     0.2499
P_30                    all     0.3100
```

Is there some sort of non-deterministic behavior (random number generator, etc.)?

**Comment by chauff** [comment]
The Indri saga continues! Let's first figure out whether that is Indri or trec_eval - can you send me your result file?

**Comment by ryan-clancy** [comment]
Here are the run files: https://drive.google.com/file/d/1AeLkJftvNFYMe1eFh_2QIPoQk99Yb-ZA/view?usp=drivesdk

**Comment by chauff** [comment]
Thanks. There are slight differences in the retrieval status scores. To ilustrate here are a few lines of the LM with Dirichlet smoothing (mu=1000, no_prf) ... yours:
```
301 Q0 FBIS4-41991 1 -5.33292 indri
301 Q0 FBIS4-55395 2 -5.54003 indri
301 Q0 FBIS3-23986 3 -5.56616 indri
```

mine:
```
301 Q0 FBIS4-41991 1 -5.3331 indri
301 Q0 FBIS4-55395 2 -5.54057 indri
301 Q0 FBIS3-23986 3 -5.56648 indri
```
Running the same command on the same machine multiple times leads to the same result, so it should not be due to a random number generator. 

Another possibility is that the index created is slightly different. I have added another line to the indexing step - it prints out the manifest file (basic info on the number of terms, documents, etc.) the Indri indexing process creates. Can you create the image again, run the indexing step (`python3 run.py prepare ... `) and post here what your manifest looks like?

Mine looks as follows:
```
<parameters>
	<code-build-date>Jun 14 2019</code-build-date>
	<corpus>
		<document-base>1</document-base>
		<frequent-terms>10841</frequent-terms>
		<maximum-document>522789</maximum-document>
		<total-documents>522788</total-documents>
		<total-terms>251134556</total-terms>
		<unique-terms>661822</unique-terms>
	</corpus>
	<fields></fields>
	<indri-distribution>Indri release 5.11</indri-distribution>
	<type>DiskIndex</type>
</parameters>
```

**Comment by ryan-clancy** [comment]
It looks like the content being indexed is slightly different:
```
::::::::::::::
/robust04/index/1/manifest
::::::::::::::
<parameters>
        <code-build-date>Jun 15 2019</code-build-date>
        <corpus>
                <document-base>1</document-base>
                <frequent-terms>10886</frequent-terms>
                <maximum-document>528156</maximum-document>
                <total-documents>528155</total-documents>
                <total-terms>253367449</total-terms>
                <unique-terms>664438</unique-terms>
        </corpus>
        <fields></fields>
        <indri-distribution>Indri release 5.11</indri-distribution>
        <type>DiskIndex</type>
</parameters>
```

**Comment by chauff** [comment]
You have significantly more documents in your corpus than I have in mine .... 522,788 vs. 528,155 - that's a 6K document difference. According to the TREC overview paper on [Robust04](https://trec.nist.gov/pubs/trec13/papers/ROBUST.OVERVIEW.pdf) 528K is correct. Looks like my corpus is slightly off.

**Comment by chauff** [comment]
We should use your effectiveness numbers in this case, I'll have to check what I did to my corpus to make it slightly different from the original. Can you update them?

**Comment by chauff** [comment]
That is actually a problem we haven't really solved yet - we probably need to report sanity check numbers on the corpora (like the total number of indexed documents) too.

**Comment by chauff** [comment]
Fixed now in latest commit (got the original corpus). Numbers are updated.

**Comment by lintool** [comment]
@r-clancy I'll let you merge... but I think we're ready for a release after?

**Review by ryan-clancy — APPROVED** [review]

**Comment by ryan-clancy** [comment]
@lintool @chauff Yep, we're all good to tag a `v0.1.0` here. I'll go ahead and do that then start doing the first of the official runs...

**Pull request merged**
